### ISSUE TITLE
Optimise image placing workflow. 

### ISSUE THREAD

**Issue by isundaylee** [TheMITTech/thetech.com#373]
From @wnavarre: 
- Saves take a very long time. (I'd estimate up 3-5 seconds in the worst case). 
- No obvious indication of which articles in lists have work needing to be done. (I think this is a more general problem...).
- Lots of returning to / from the list of articles. (Basically, to get from one article to another, two clicks are required. Given the laggy nature of the website, it feels frustrating).

**Comment by CyanoKobalamyne** [comment]
Images are no longer placed manually.
