### ISSUE TITLE
updating an old draft puts it in current issue...

### ISSUE THREAD

**Issue by charliemj** [TheMITTech/thetech.com#436]

**Comment by isundaylee** [comment]
Hmm I can't seem to reproduce this issue.. Is it showing up as belonging to the current issue in the CMS? Or is it just showing up on the homepage?

**Comment by kar-moore** [comment]
This article https://thetech.com/2015/10/15/application-v135-n27

appears in https://thetech.com/issues/137/30

after I updated the primary tag of the article

**Comment by tareqdandachi** [comment]
This should have been fixed by commit 4fab253 (the fix for #444).
