### ISSUE TITLE
Two things related to Science

### ISSUE THREAD

**Issue by Starnite** [TheMITTech/thetech.com#444]
1. Can you add Science to the header bar so that one can navigate to a page with all science articles from the homepage, as you can with all the other sections?
2. There are two articles written by Theresa Machemer that are currently under News with Primary Tag Science Column. Can you change these to be under Science, but keep the same issue number? When I edit from CMS it only goes back to N25.

**Comment by tareqdandachi** [comment]
<img width="1440" alt="screen shot 2018-11-05 at 6 58 37 pm" src="https://user-images.githubusercontent.com/27817478/48034333-faf57100-e12c-11e8-8f44-cd42055714a9.png">

@Starnite for Issue 1, do you mean add "Science" to the menu bar (Blue arrow) the same way "Science" is in the navigation bar (The red arrow)?

**Comment by tareqdandachi** [comment]
Fixed part 1 of the problem. Not part 2.

**Comment by tareqdandachi** [comment]
Ignored part 2 for a long time, for this, I was thinking of adding an option in the CMS to overcome the "max 10 limit" for issues, it would be something of the form: keep current issue number (or in the options force it to include the current issue number along side the latest 10 issues).

**Comment by CyanoKobalamyne** [comment]
The articles still need to be moved so let's keep this open.
