### ISSUE TITLE
Saving article should go to the new article detail page

### ISSUE THREAD

**Issue by isundaylee** [TheMITTech/thetech.com#454]

**Comment by tareqdandachi** [comment]
Could you please clarify?

Currently:
When Update is clicked, a preview for the article is shown.
When Save is clicked, it saves and stays on the same page.

What you want is that when Save is clicked it takes you out of edit mode and back to the view where all the different drafts are shown (As if you were to click the back button)? If this is what you mean, how would a user save his work mid-progress to avoid losing it without having to exit and reopen the link?
