### ISSUE TITLE
Long word in article title causes overflow of word (new line starts only on new word)

### ISSUE THREAD

**Issue by itstorque** [TheMITTech/thetech.com#465]
<img width="209" alt="screen shot 2018-11-12 at 9 09 02 pm" src="https://user-images.githubusercontent.com/27817478/48386202-30ff9b80-e6bf-11e8-9d42-c5ae94d36b52.png">

**Comment by tareqdandachi** [comment]
Also added a 3 line limit using webkit line clamp
