### ISSUE TITLE
Wrong blurb on issue page

### ISSUE THREAD

**Issue by CyanoKobalamyne** [TheMITTech/thetech.com#481]
An article in the [most recent issue](https://thetech.com/issues/138/31) has the wrong teaser blurb displayed. See below:

![kepernyokep errol 2018-12-06 03-01-36](https://user-images.githubusercontent.com/4078712/49570473-ac421f00-f904-11e8-8e28-3842d3fe023b.png)

**Comment by CyanoKobalamyne** [comment]
This is still the case.

**Comment by bkettle** [comment]
Seems to be resolved. Closing until/unless this comes up again.
