### ISSUE TITLE
"Read More" Section Is Inconsistent With Design Language

### ISSUE THREAD

**Issue by VMReyes** [TheMITTech/thetech.com#519]
At the end of every article, there is a "Read More" section to pre-filled tag searches. The section is identified by a red rectangle with the words "Read More".

However, this design choice conflicts with the overall color theme and language of the website. Most clickable/actionable links are presented in red, and at the very top of the page we have a similar looking button to "Submit Campus Life Stories". The "Read More" "button" is actually not actionable and therefore should not have a red color. Its usage of capitalization is also incoherent with the rest of the section, which uses all uppercase letters.

**Comment by VMReyes** [comment]
Before:
![image](https://user-images.githubusercontent.com/29768771/65772936-4a5bdb80-e109-11e9-92d4-5c98ca58e2f0.png)
After:
![image](https://user-images.githubusercontent.com/29768771/65772974-5cd61500-e109-11e9-80d4-54f2abb3593e.png)

**Comment by tareqdandachi** [comment]
See issue #512

**Comment by VMReyes** [comment]
Got it. Thanks!
